### ISSUE TITLE
this.field(name).value returns undefined in 2.3.3

### ISSUE THREAD

**Issue by satyavh** [aldeed/meteor-simple-schema#340] opened 2015-04-17 15:45 UTC
Just upgraded to 2.3.3 and noticed that custom validation is suddenly not working anymore. Seems that this.field(name).value in custom validation always returns undefined. Here's my code

```
    new SimpleSchema(
      currentPassword:
        type: String
        min: 4
        instructions: 'Current password'
        label: 'Current password'
      newPassword:
        type: String
        min: 4
        label: 'New password'        
      confirmPassword:
        type: String
        min: 4
        label: 'Confirm new password'   
        custom: ->
          if @value != @field('newPassword').value 
            return "passwordMismatch"
```

@field('newPassword').value returns undefined. Before latest verion this was working just fine

**Comment by mattkrick** [comment] 2015-04-18 23:31
I'm having the same problem with both `field` and `siblingField`. Failed tests on arrays, nestsed schemas, and plain old simple ones.

**Comment by satyavh** [comment] 2015-04-19 19:27
good to hear I'm not the only one. I've tried SiblingField as well, same undefined result.

**Comment by rclai** [comment] 2015-04-22 20:19
I'm in the context of an autoform submission and I've noticed that not only are `this.field('...')`'s values wrong, but `this`'s `value` and `isSet` are `undefined` and `false`, respectively.

**Comment by mattkrick** [comment] 2015-04-22 20:26
I think that has to do with the validation on blur & is an autoform issue,
this issue is without autoform.

**Comment by rclai** [comment] 2015-04-22 20:51
Oh wait, never mind my issue, false alarm.

**Comment by gerwinbrunner** [comment] 2015-06-22 19:40
I do have the same issue just right now. :(
:+1:

**Comment by Miniwe** [comment] 2015-06-24 19:07
If you try save whole scheme then all right, if you try to update some field then we get undefined in  this.field

**Comment by orion4567** [comment] 2015-09-03 22:39
I appear to be having the same issue when attempting to create a user account with Accounts.createUser. I'm trying to debug, and it appears that  autovalue is being called twice on the server. The first time this.field('field').value is defined correctly, when autovalue runs again immediately after it's undefined and unset. Anyone have any insight?

**Comment by dbismut** [comment] 2015-10-29 13:50
I think I have the same problem. Here's my custom approval function:

```javascript
amount: {
  type: Number,
  decimal: true,
  custom: function () {
    let currency = this.field('currency').value;
    let transactionMinimumAmount = Currencies.findOne({
      code: currency
    }).transactionMinimumAmount;
    if (this.value < transactionMinimumAmount) {
      return 'minNumber'; // #TODO:90 change error message  
    }
  }
}
```

When I update my collection without setting the currency, `this.field('currency')` returns `undefined`:
```javascript
Plans.update(_id, {$set: {amount: 10}}) // this.field('currency') is undefined
```

However, `this.field('currency')` returns the expected value when I update my collection while setting the currency in the query.
```javascript
Plans.update(_id, {$set: {amount: 10, currency: "USD"}}) // this.field('currency') is the correct object
```

**Comment by aldeed** [comment] 2015-11-26 13:05
I think this is fixed in the v2 I'm working on, but to be sure, I'll need someone to post a link to a simple app that reproduces the issue consistently.

**Comment by edvinsalo35** [comment] 2016-03-05 13:32
This issue happens yet. 

In this.field, this returns blank object {}, so this.field is undefined. 

I hope to know if it's only my issue yet.

**Comment by jakobloekke** [comment] 2016-05-17 09:18
Here's a sample app, which is a slice of a larger app I'm currently working on, where we're having this issue.
https://github.com/jakobloekke/simple-schema-issue-340-repro/tree/master
https://www.youtube.com/watch?v=l7GXF5eMGOk

In short, we have an account url ('slug') which is auto generated from an AccountName field.
This works on inserts but not on updates, causing the value to become empty.

From the documentation I am unsure if this is expected behaviour. 
But it feels like a bug to us. :)

**Comment by minfawang** [comment] 2016-05-21 18:16
I have encountered the same issue. The comment above summarized it perfectly!

**Comment by minfawang** [comment] 2016-05-21 19:06
Add 2 cents here: 
~~~javascript
import { SimpleSchema } from 'meteor/aldeed:simple-schema';
const User = new SimpleSchema({
  userId: {
    type: String,
    optional: true,
  },
  email: {
    type: String,
    optional: true,
    custom() {
      // Output: Object {isSet: false, value: undefined, operator: undefined}
      console.log(this.field('userId')); // <---

      if (!this.field('userId').value && !this.value) {
        return 'required';
      }
      return null;
    },
  },
});

const schema = new SimpleSchema({
  user: { type: User },
});

const doc = { user: { userId: 'abc' } };
schema.validate(doc);
~~~

You can just copy and paste the above snippet below to see the error. Looks like it happens to the nested schema.

**Comment by minfawang** [comment] 2016-05-21 20:31
Sorry. Please disregard my comments above. Just inspected the code and doc, and realized I should use `siblingFiled` in this scenario.

**Comment by Xplic1T** [comment] 2016-07-11 05:22
Has any progress been made on this? Just got this on my end and having issues circumventing it. 

this.somekey returns undefined but the quickform will display ... my validation fails however

this.field('somekey').value errors out underfined and just displays a box the whole width of the form.

**Comment by aldeed** [comment] 2016-08-24 01:09
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.

**Closed by aldeed** 2016-08-24 01:09 UTC
Labels: needs reproduction, potential bug

**Comment by smartdemocracy** [comment] 2016-09-15 08:39
https://www.npmjs.com/package/simpl-schema
