### ISSUE TITLE
Validate Objects with Keys as Document Ids

### ISSUE THREAD

**Issue by fardeemmunir** [aldeed/meteor-simple-schema#444] opened 2015-09-05 13:09 UTC
I have an object inside a document that looks like this:

```.js
var obj = {
  ...
  bnsgSfNgZX8pyvhKW: [
    [ 'sss', 2 ], [ 'ddd', 5 ]
  ]
  ...
}
```

So basically the keys of the objects are document ids corresponding to another collection and each key has an array that contains an arbitary amount of arrays that has a string as the first element and a number as the second element.

Using `blackbox: true' works but I don't want to use it. Is there any way to add validation for this. I tried this:

```
custom: function() {
      Object.keys( this.value ).every( id => { 
        return SimpleSchema.RegEx.Id.test( id ) ? true : 'false';
      });
}
```

but it didn't work.

Also, is my schema design absolutely the worst!

**Comment by aldeed** [comment] 2015-11-12 14:25
Duplicate of #213

**Closed by aldeed** 2015-11-12 14:25 UTC
