### ISSUE TITLE
Custom clean method?

### ISSUE THREAD

**Issue by j20** [aldeed/meteor-simple-schema#428] opened 2015-08-13 20:10 UTC
Is it possible to create a custom clean method?

For example, my use case would be for a method that would round input values from (#.###...) to a set degree of precision (#.#)

**Comment by attackant** [comment] 2015-09-09 02:33
I'm looking for a way to this as well. Any leads @j20 ?

**Comment by j20** [comment] 2015-09-23 04:28
@attackant Not yet. Would be a nice feature to have though.

**Comment by aldeed** [comment] 2015-11-12 15:27
Duplicate of #406

**Closed by aldeed** 2015-11-12 15:27 UTC

**Comment by j20** [comment] 2015-11-21 22:39
@attackant I found a way to achieve this based on the linked issue #406  Add this within any of your simple schema properties to modify the value before it is saved.

        autoValue: function () {
          if (this.isSet && Meteor.isServer) {
            return this.value + 100;
          }
        },

**Comment by j20** [comment] 2015-11-21 23:26
It's worth mentioning that unfortunately, unlike clean, this doesn't run before validating the data. For instance, if your schema expects an integer, you want to round the input, and a decimal is provided as the input then a validation error "Must be an integer" will be shown, instead of the rounding occurring before validation to avoid this. So it doesn't work in all cases. Still would be better have to a custom clean method.

**Comment by attackant** [comment] 2015-11-23 16:20
@j20 thank you for the follow up.

**Comment by wojtek-krysiak** [comment] 2016-06-23 21:04
This worked for me: 

```
var _originalClean = SomeSchema.clean;
SomeSchema.clean = function() {
  var doc = arguments[0];
  var options = arguments[1];
  doc.paramToBeCleaned = doc.paramToBeCleaned + 100;
  _originalClean.call(this, doc, options);
};
```
