### ISSUE TITLE
Default values for nested schema

### ISSUE THREAD

**Issue by sungwoncho** [aldeed/meteor-simple-schema#418] opened 2015-07-24 05:55 UTC
I am unable to set `defaultValue` for fields in a nested schema.

Here is an example:

```javascript
Schema.users = new SimpleSchema({
...
  stats: {
    type: Schema.stats,
  }
});

Schema.stats = new SimpleSchema({
  topicCount: {
    type: Number,
    defaultValue: 0
  }
});

Meteor.users.attachSchema(Schema.users);
```

When a user document is created, I expect the `stats.topicCount` to be set to `0` when `stats` is not supplied. Instead, Meteor throws:

    Stats is required [400]

Is this an expected behavior, and is there a way to set default values for fields in a nested schema?

**Comment by v3rron** [comment] 2015-07-26 16:34
Same here...

**Comment by gabrielpoca** [comment] 2015-09-16 17:34
@sungwoncho I'm not able to reproduce, is it still occurring?

**Comment by TWKDreamState** [comment] 2015-09-16 21:19
I am also finding this at the moment. On a nested schema, unless I specifically apply a default in my code, I get an 'is required' error if I do not supply it.

**Comment by gabrielpoca** [comment] 2015-09-16 23:58
@TWKDreamState please see if this code makes sense to reproduce the error:

```
AuthorsSchema = new SimpleSchema({
  rank: {
    type: Number,
    defaultValue: 0
  }
});

PostsSchema = new SimpleSchema({
  name: {
    type: String,
    defaultValue: 'Name'
  },
  author: {
    type: AuthorsSchema,
  }
});

Posts = new Mongo.Collection('posts');

Posts.attachSchema(PostsSchema);
```

When I run `Posts.insert({})` I get a success response.

```
{ _id: 'Dpg9GJcShHWQzBudm',
  name: 'Name',
  author: { rank: 0 } }
```

Would this result in an error for you or am I not understanding the issue?

**Comment by TWKDreamState** [comment] 2015-09-17 08:04
@gabrielpoca thanks for your help on this. Just at work at the moment (coding is my evening job!) so will take a look tonight.

Just initially the key differences for my code is that the embedded documents are arrays (so in your example it would be ..

    author: {
        type: [AuthorsSchema]
    }

..but also I am calling an update, so I may have misunderstood the defaultValue - does it only apply to inserts? I was thinking that as the sub-document doesn't yet exist that the defaultValue would work when the model as a whole is updated - perhaps this is the issue?

**Comment by gabrielpoca** [comment] 2015-09-17 13:28
@TWKDreamState if it's an array you need to define the default value as an empty array, like this:

```js
AuthorsSchema = new SimpleSchema({
  rank: {
    type: Number,
    defaultValue: 0
  }
});

PostsSchema = new SimpleSchema({
  name: {
    type: String,
    defaultValue: 'Name'
  },
  author: {
    type: [AuthorsSchema],
    defaultValue: []
  }
});
```

Let me know if this works for your.

**Comment by ramijarrar** [comment] 2015-09-17 15:30
@sungwoncho the error here is not being caused by simple schema not being able to assign default values, but rather a required field within the nested schema that does not also have a default value.

So in your example above @gabrielpoca all you need to do to reproduce the error is add another field which is required:

```
AuthorsSchema = new SimpleSchema({
  rank: {
    type: Number,
    defaultValue: 0
  },
  foo: {
     type: String
  }
});

PostsSchema = new SimpleSchema({
  name: {
    type: String,
    defaultValue: 'Name'
  },
  author: {
    type: AuthorsSchema,
  }
});

Posts = new Mongo.Collection('posts');

Posts.attachSchema(PostsSchema);
```
@TWKDreamState I don't think embedded arrays vs objects is relevant here

**Comment by gabrielpoca** [comment] 2015-09-17 16:16
@ramijarrar I that scenario an error would be expected, that's what I was trying to understand.

But my understanding is that embedded arrays are different from objects. If all fields in a nested object have default values, you don't need a default value for the object itself. Take the following as an example.

```js
AuthorsSchema = new SimpleSchema({
  rank: {
    type: Number,
    defaultValue: 0
  }
});

PostsSchema = new SimpleSchema({
  name: {
    type: String,
    defaultValue: 'Name'
  },
  author: {
    type: AuthorsSchema
  }
});

Posts = new Mongo.Collection('posts');
Posts.attachSchema(PostsSchema);

Posts.insert({});
```

But if the embedded object is an array, then the array field needs a default value. The following example should show the difference between default values for embedded objects and arrays.

```js
AuthorsSchema = new SimpleSchema({
  rank: {
    type: Number,
    defaultValue: 0
  }
});

PostsSchema = new SimpleSchema({
  name: {
    type: String,
    defaultValue: 'Name'
  },
  author: {
    type: [AuthorsSchema],
    defaultValue: []
  }
});

Posts = new Mongo.Collection('posts');
Posts.attachSchema(PostsSchema);

Posts.insert({});
```

I tested this understanding of the internals is vague.

**Comment by aldeed** [comment] 2015-11-12 15:15
Trying to get caught up here. Is there any issue? Array items cannot have default values by design because that doesn't make any sense, but if the array items are objects, then each object could have default values I think. And child object defaults should work fine, too, to any level of nesting.

`defaultValue` is just a shortcut for this `autoValue`:

```js
if (this.operator === null && !this.isSet) {
  return v;
}
```

So they only apply to inserts.

**Comment by gabrielpoca** [comment] 2015-11-12 15:54
I'm not sure, but I think it is more a matter of understanding how it works.

**Comment by bigSmallio** [comment] 2015-12-30 18:04
Hey, I'm experiencing this issue too.  The [Object] discussion is way off-topic.  I made a new issue: #527

**Comment by soitech** [comment] 2016-01-21 19:23
I also seem to be experiencing this, and I don't think I used to have this issue. Just recently noticed an "is required" exception using a schema I've had in place for 8 or 9 months. 

Here are some of the applicable parts:
~~~javascript 
StudentsBaseSchema = new SimpleSchema({
    tests: {
	type: [Object],
	defaultValue: []
    },

    'tests.$': {
        type: Object,
        optional: true
    }
});

AlaScoresSchema = new SimpleSchema({
	'CFC':{
		type: Number,
		max: 15,
		min: -1,
		autoform:{
			capitalize:true,
			label:'CFC',
		},
		defaultValue: -1,
	}
});

AlaStudentsSchema = new SimpleSchema([StudentsBaseSchema,
  {
    'tests.$.scores':{
      type:AlaScoresSchema
    }
  }
]);

~~~~~

Some testing shows it works fine on insert, but not on update, even though clean() is being called in either instance.

**Comment by dsinghr** [comment] 2016-05-14 13:41
Simple trick worked for me. Removed "defaultValue" and added "autoValue" function instead.

**Comment by aldeed** [comment] 2016-09-12 18:45
I think this is just misunderstanding so I'm closing this.

**Closed by aldeed** 2016-09-12 18:45 UTC
Labels: potential bug, waiting for details

**Comment by v3rron** [comment] 2016-09-12 18:57
Only last couple of comments were a misunderstanding with improper use of arrays. The main issue is still ongoing. 
If you look at the comment the issue was created with, the nested schema is another schema that one would expect to be prefilled with default values, even if not provided in a query, since the field is required. But instead, it throws an error:
````
Stats is required [400]
````
I use those nested schemas and expect to always have them in DB, even if I didn't interact with them yet. We just need an option to have a schema that is not optional, but one that you don't have to provide in a query, every time you interact with a parent object.

**Comment by soitech** [comment] 2016-09-12 19:07
I don't think my issue was a misunderstanding. But maybe I'm wrong in thinking using a schema in type: would be an object, not an array, and thus should use it's default values. Plus, it works on insert, but not update, so that seems like a valid issue. 

But, I apparently found some sort of workaround since it popped up in June for me, so closing doesn't effect me.

**Comment by aldeed** [comment] 2016-09-12 19:40
As the documentation notes:

> Default values are set only when cleaning non-modifier objects.

https://github.com/aldeed/meteor-simple-schema#defaultvalue

So if it works for insert, it works. `defaultValue` is a very limited option that simplifies a very specific use case for `autoValue`, but if it doesn't cover what you need, you'd need to use `autoValue` instead.

If you really think there's a bug here and you can provide a small reproduction app to show it, that would help if I'm misunderstanding this.

**Comment by soitech** [comment] 2016-09-12 20:18
No, for my part it's fine. You certainly understand the functionality better than I do, and if in your opinion it is working as intended, I trust that.
