### ISSUE TITLE
The object as an array

### ISSUE THREAD

**Issue by ivansglazunov** [aldeed/meteor-simple-schema#538] opened 2016-01-18 08:11 UTC
https://en.wikipedia.org/wiki/Hash_table
I need to describe schema as array, but in relation to the object.
As an example:
```js
new SimpleSchema({
    myObj: {
        type: new SimpleSchemaTable({
            type: String
        })
    }
});
```
What can I do to appear a functional? Create a separate package adds "some" SimpleSchemaTable or make a pull request?

**Comment by aldeed** [comment] 2016-08-24 01:46
Seems to be a duplicate of #244

**Closed by aldeed** 2016-08-24 01:46 UTC
