### ISSUE TITLE
A way to validate fields of schema, but ignore extra fields?

### ISSUE THREAD

**Issue by trusktr** [aldeed/meteor-simple-schema#407] opened 2015-07-09 17:25 UTC
I'd like to make a Schema to validate collections with using Collection2, but I'd like for the validation to ignore fields that aren't listed in the schema. Is this possible to do?

For example, if I have

```js
Items = new Mongo.Collection('Items')

Items.attachSchema(new SimpleSchema({
  foo: {
    type: String
  },
  bar: {
    type: String
  }
}))
```

I want the validation to fail if I do something like

```js
Items.insert({
  foo: 1, // Fails: not a string.
  bar: "bar",

  // ignore the rest:
  blah: "blah"
})
```

but I want it to pass if I do something like

```js
Items.insert({
  foo: 'foo',
  bar: "bar",

  // ignore the rest:
  blah: "blah",
  lorem: 23,
  random: "asdfh",
})
```

where it only checked the `foo` and `bar` properties. Any other properties can be random for now, we don't know what they'll be. I was wondering if it's possible to do this for prototyping, then later I'll make everything strict.

**Comment by harmon25** [comment] 2015-07-22 17:36
Create a blackbox object and place extra properties within it it.
```
Items = new Mongo.Collection('Items')

Items.attachSchema(new SimpleSchema({
  foo: {
    type: String
  },
  bar: {
    type: String
  },
 extras:{
   type:Object,
   blackbox: true
 }
}))
```
Inserting would go something like this, blackbox objects will not be validated:
From the docs: "...use the blackbox: true option to skip validation for everything within the object."
```
Items.insert({
  foo: 'foo',
  bar: "bar",

  // ignore the rest:
  extras.blah: "blah",
  extras.lorem: 23,
  extras.random: "asdfh"
})
```

**Comment by pavanputhra** [comment] 2015-08-22 16:26
+1

**Comment by aldeed** [comment] 2015-11-10 23:43
Duplicate of #213

**Closed by aldeed** 2015-11-10 23:43 UTC
