### ISSUE TITLE
Free choose of Objects-property but validating the rest

### ISSUE THREAD

**Issue by TimoRuetten** [aldeed/meteor-simple-schema#484] opened 2015-10-28 13:39 UTC
Hey! Is there any way to tell simple schema that a objects property is free to choose but its content has to be validated ?

Reference on Stackoverflow: http://stackoverflow.com/questions/33392559/meteorjs-simpleschema-dont-validate-object-property-names-but-its-content

**Comment by aldeed** [comment] 2015-11-12 22:27
Duplicate of #213

**Closed by aldeed** 2015-11-12 22:27 UTC
