### ISSUE TITLE
GeoJSON coordinates should be easier to schema

### ISSUE THREAD

**Issue by johnslemmer** [aldeed/meteor-simple-schema#606] opened 2016-05-11 22:58 UTC
Mongo uses [GeoJSON](https://docs.mongodb.com/manual/reference/geojson/) data structures for storing location.  And the way they store coordinates is in an array `[ <longitude>, <latitude> ]`.  However, creating a schema for that type of coordinate seems harder than it needs to be.

Here is how I'm solving the problem today:

```
  RectangleCoordinatesSchema = new SimpleSchema({
    coordinates: {
      type: Array,
      minCount: 2,
      maxCount: 2,
    },
    'coordinates.$': {
      type: [Number],
      decimal: true,
      minCount: 2,
      maxCount: 2,
      custom: function custom() {
        if (!(-90 <= this.value[0] <= 90)) {
          return 'lngOutOfRange';
        }
        if (!(-180 < this.value[1] <= 180)) {
          return 'latOutOfRange';
        }
        return true;
      },
    },
  })
```

However, anytime I want to have another schema object that includes a GeoJSON type coordinate value I need to copy and paste around the following code. 

```
      type: [Number],
      decimal: true,
      minCount: 2,
      maxCount: 2,
      custom: function custom() {
        if (!(-90 <= this.value[0] <= 90)) {
          return 'lngOutOfRange';
        }
        if (!(-180 < this.value[1] <= 180)) {
          return 'latOutOfRange';
        }
        return true;
      },
```

This is not ideal, and is not good coding. However, if I could have a schema object that I could reuse for coordinates and then my example would be more like the following:

```
CoordinatesSchema = new SimpleSchema({
  0: {
    label: 'longitude',
    type: Number,
    decimal: true,
    max: 180.0,
    min: -180.0,
    exclusiveMin: true,
  },
  1: {
    label: 'latitude',
    type: Number,
    decimal: true,
    max: 90.0,
    min: -90.0,
  },
});

  RectangleCoordinatesSchema = new SimpleSchema({
    coordinates: {
      type: CoordinatesSchema,
      minCount: 2,
      maxCount: 2,
    },
  })
```

NOTE: the above code does not work because you can not have numbered keys.  An error is raised `TypeError: Cannot read property 'blackbox' of undefined`.  There are some other issues that touch on this bug.

First, is there a better way to accomplish what I'm doing?  And if not can simple-schema potentially add support for validating against specific array indexes (and implicitly the length of an array value)?

**Comment by proehlen** [comment] 2016-05-29 10:32
Having the exact same problem with storing wavesurfer.js sprites - the keys are zeros unfortunately so I've blackboxed the whole property.

**Comment by clayne11** [comment] 2016-07-08 20:38
Why don't you simply create a reusable schema and compose it into new schemas when you have one that needs it?

**Comment by Pushplaybang** [comment] 2016-07-25 18:40
I've got to agree with @clayne11, this seems like a non-issue, what's stopping you composing schema? @johnslemmer

**Comment by krishaamer** [comment] 2016-08-03 08:59
Also have this question (GeoJSON could be addressed in the docs). So what's the most elegant solution to this?

**Comment by proehlen** [comment] 2016-08-04 00:31
@clayne11 @pushplaybang

> NOTE: the above code does not work because you can not have numbered keys. An error is raised TypeError: Cannot read property 'blackbox' of undefined.

**Comment by aldeed** [comment] 2016-09-13 23:37
If the numeric keys are the only problem here, then this is a duplicate of https://github.com/aldeed/meteor-simple-schema/issues/310.

I didn't get that fixed in v2 since it is rather tricky, but I will try for a v3 that fixes it. It will have to be another major version bump because we'll have to change array dot notation to `a.[1].b` or something similar so that we can distinguish between numeric keys and array indexes.

**Closed by aldeed** 2016-09-13 23:37 UTC
