### ISSUE TITLE
Overwriting SimpleSchema regEx messages

### ISSUE THREAD

**Issue by vfonic** [aldeed/meteor-simple-schema#720] opened 2017-11-14 21:36 UTC
I just realized that doing this:

```js
SimpleSchema.messages({
  regEx: [{ exp: SimpleSchema.RegEx.Url, msg: 'URL is not a valid URL' }],
});
```

...removes all other `regEx` validation error messages and I'm getting a lot of "Unknown validation error" for, for example `SimpleSchema.RegEx.Email`. Is there a way to append/replace only a single `exp`?

**Comment by brooksbecton** [comment] 2017-11-27 20:16
Do you have your code hosted some where? 


It seems like it should be working.

[Here](https://github.com/aldeed/meteor-simple-schema/blob/master/simple-schema.js#L946) is the line that combines the messages. It basically spreads the previous messages with messages that you supply using [lodash's extend](https://lodash.com/docs/4.17.4#assignIn)

I did a [Code Pen](https://codepen.io/brooksbecton/pen/Kyxqqx) where I copied the default messages and "extended" in a new message and it seems to be working.

**Comment by brooksbecton** [comment] 2017-11-28 01:35
Gotta another [pen here](https://codepen.io/brooksbecton/pen/qVMjga?editors=0012) that shows how mergeWith can combine the two.

**Comment by vfonic** [comment] 2017-11-28 16:52
Thanks @brooksbecton!

What do you suggest would be the best way to use this in my project's code? Should I just directly manipulate `SimpleSchema._globalMessages`?

Do you think this should be added to the simple-schema code itself? I'm really swamped right now, but if I find some time I could submit a PR.

**Comment by brooksbecton** [comment] 2017-11-28 18:39
According to the README
`NOTE: "v2" of this package is an NPM package. Please use the NPM package even in Meteor apps. This Meteor package will get only critical fixes...`

This seems important, but it is up to the maintainers on whether this is a critical fix or not. 

The npm package for [simple-schema-js](https://github.com/aldeed/simple-schema-js) is using [extend](https://www.npmjs.com/package/extend) which does properly spread the default messages with the new messages. So if you can migrate over to it, that would probably be best. 

---

Also wanted to note here that this repo is using underscore.js not lodash.

**Comment by aldeed** [comment] 2018-04-11 22:31
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able

**Closed by aldeed** 2018-04-11 22:31 UTC
