### ISSUE TITLE
this.field('...') doesn't seems to work anymore

### ISSUE THREAD

**Issue by Firfi** [aldeed/meteor-simple-schema#412] opened 2015-07-15 13:02 UTC
I have custom validation on field in schema. (custom: ...)

I have sibling field (it called 'profile') with subfields (one of them is 'accountType')

If I write `this.field('profile.accountType').value` in `custom`, it gives me undefined, through both profile and accountType are defined in entity I trying to validate.

I'm sure it used to work before, at least I have those calls in my schema for another entities.

**Comment by Firfi** [comment] 2015-07-15 13:12
The same states for autoValue. Perhaps I'm doing something wrong, but I remember clearly it used to work before for another fields that have same structure (i.e. this.field(...) is called inside sibling)

**Comment by Firfi** [comment] 2015-07-15 13:46
The same happens when I move my field inside `profile` (so it have `accountType` as a sibling).

Neither `this.field('accountType')` nor `this.field('profile.accountType')` then doesn't seems to return field with value (it returns a field without value and with isSet: false).

**Comment by johanbrook** [comment] 2015-07-27 11:53
I also get this, unless I'm doing something wrong. I've got this:

```coffeescript
CommentSchema = new SimpleSchema(
  text:
    type: String
  createdAt:
    type: Date
  modifiedAt:
    type: Date
    denyInsert: true
    optional: true
    custom: ->
      createdAt = @field('createdAt').value
      return 'minDate' if moment(@value).isBefore(createdAt)
```
On update, the validation for `modifiedAt` returns the error string, even though it shouldn't. `createdAt` above yields this when logging: `{ isSet: false, value: undefined, operator: undefined }`.

**Comment by solace** [comment] 2015-08-24 11:33
I'm seeing similar issues with both this.field and this.siblingField in custom validation.

**Comment by joshfttb** [comment] 2015-09-04 01:49
So I need to test more, but this seems to work:

    autoValue: function() {
             if (Meteor.isServer && !this.isSet && this.field('emails').isSet){
                 var uname = this.field('emails').value[0].address.replace(/@(.*)/, "");
             return uname;
             }
    }


While this seems to fail silently half the time:
    autoValue: function() {
             if (Meteor.isServer && !this.isSet){
                 var uname = this.field('emails').value[0].address.replace(/@(.*)/, "");
             return uname;
             }
    }

**Comment by joshfttb** [comment] 2015-09-04 03:25
Just realized my first post on this topic was on a similiar issue https://github.com/aldeed/meteor-simple-schema/issues/340

**Comment by aldeed** [comment] 2015-11-26 13:03
Closing as duplicate of #340

**Closed by aldeed** 2015-11-26 13:03 UTC
Labels: needs investigation, potential bug
