### ISSUE TITLE
Causes text-typing issues (missing spaces, etc.)

### ISSUE THREAD

**Issue by Siyfion** [aldeed/meteor-simple-schema#420] opened 2015-07-28 09:40 UTC
For the full information, including a MeteorPad demoing this issue, see here: https://forums.meteor.com/t/simple-schema-collection-2-causing-text-typing-errors/7587/1

**Comment by aldeed** [comment] 2015-11-10 23:23
Probably a duplicate of #348

**Closed by aldeed** 2015-11-10 23:23 UTC
