### ISSUE TITLE
extracting schema bug

### ISSUE THREAD

**Issue by partus** [aldeed/meteor-simple-schema#427] opened 2015-08-11 16:22 UTC
var myschema = new SimpleSchema({name: {type: [String]}})
undefined
myschema.pick(["name"])
simple-schema.js:465 Uncaught Error: Invalid definition for name.$ field.

**Comment by partus** [comment] 2015-08-11 17:43
simplest hack for my needs is 

function pickSchema(schema, key){
  var allKeys = [key];
  _.each(schema.schema(), function(v,k){
    if(k.indexOf(key+'.')==0){
      allKeys.push(k)
    }
  })
  return schema.pick(allKeys)
}

**Comment by aldeed** [comment] 2015-11-10 23:40
Duplicate of #284

**Closed by aldeed** 2015-11-10 23:40 UTC
