### ISSUE TITLE
Feature request: wildcard property name

### ISSUE THREAD

**Issue by mattkrick** [aldeed/meteor-simple-schema#305] opened 2015-03-22 20:25 UTC
I have a deeply nested collection & I'd like to move away from an "array of objects" pattern so I can edit those deeply nested items efficiently.

Essentially go from this:
```
doogie = {
  foo: [
    {
      id: '123',
      baz: 'bazzle',
      bar: 'barzzle'
    },
    {
      id: '124',
      baz: 'bazzle4',
      bar: 'barzzle4'
    }
  ]
};
```

To this:
```
doogie = {
  foo: {
    '123': {
      baz: 'bazzle',
      bar: 'barzzle'
    },
    '124': {
      baz: 'bazzle4',
      bar: 'barzzle4'
    }
  }
};
```

To do that today, as I understand, I have to `blackbox` the `foo` object & then validate each subdoc when i do an insert/update to ensure `baz` and `bar` follow the schema. (If this is wrong, or there's a better pattern please let me know).

I propose moving that validate logic back to the Schema. Maybe something like this:

```
Schemas.subFoo = new SimpleSchema({
  '*WILDCARD*': {
    baz: {
      type: String
    },
    bar: {
      type: String
    }
  }
});

Schema = new SimpleSchema({
  foo: {
    type: Schemas.subFoo
  }
});
```

Thoughts or suggestions?

**Comment by aldeed** [comment] 2015-03-28 15:21
Duplicate of #244

**Closed by aldeed** 2015-03-28 15:21 UTC
