### ISSUE TITLE
TypeError: Cannot read property 'Id' of undefined (SimpleSchema.RegEx)

### ISSUE THREAD

**Issue by dandv** [aldeed/meteor-simple-schema#371] opened 2015-06-01 18:56 UTC
I'm trying to use SimpleSchema.RegEx from another package, and I'm getting

> TypeError: Cannot read property 'Id' of undefined

To reproduce, `meteor run` https://github.com/dandv/simple-schema-regex-undefined. What is the package missing?

**Comment by awei01** [comment] 2015-09-05 03:35
seems like duplicate of #390

**Comment by aldeed** [comment] 2015-11-12 14:23
Should be `api.use('aldeed:simple-schema@1.3.0');`

Without the version it pulls in a very old version of the package.

**Closed by aldeed** 2015-11-12 14:23 UTC

**Comment by JulianKingman** [comment] 2016-10-04 20:09
How does this work with react, ie `import SimpleSchema from 'meteor/aldeed:simple-schema';`?
