### ISSUE TITLE
unable to pick schema key of type array  

### ISSUE THREAD

**Issue by pociej** [aldeed/meteor-simple-schema#430] opened 2015-08-17 16:45 UTC
```
Schemas.TestSchema = new SimpleSchema({
  test : {
    type : String ,
  }
});

Schemas.MySchema = new SimpleSchema({
  myField : {
    type : [Schemas.TestSchema]
  }
});
```

then 

```
Schemas.MySchema.pick('myField')
Error: Invalid definition for myField.$ field.

``` 

confusing...

**Comment by raptor008** [comment] 2015-09-03 19:20
Looks like I'm having luck passing both "myField" and "myField.$". E.g.,

```
Schemas.MySchema.pick('myField', 'myField.$');
```

**Comment by jholl** [comment] 2015-10-01 14:40
This worked for me; and if anyone comes across in the future, also when I had

    type: [String],

and wanted to pick it, I needed to include `fieldname, fieldname.$` in my pick

**Comment by aldeed** [comment] 2015-11-12 20:13
Duplicate of #284

**Closed by aldeed** 2015-11-12 20:13 UTC
