### ISSUE TITLE
Defining a schema with flexible keys

### ISSUE THREAD

**Issue by lourd** [aldeed/meteor-simple-schema#329] opened 2015-04-08 18:24 UTC
In this use case, I have a document where I want to do some validation on the values in each key-value pair. I don't care about the format of the key, just the value. Here's an example:

```js
var valueSchema = new SimpleSchema({
  value: {
    type: Number
  },
  updatedAt: {
    type: Date
  },
  addedBy: {
    type: String
  }
});

documentSchema = new SimpleSchema();
documentSchema.addValidator( function() {
  console.log("CUSTOM VALIDATOR");
  if ( ! _.isNull(this.value) && ! Match.test(this.value, valueSchema) ) {
    return "The value for this key is invalid!";
  }
});

d = documentSchema.newContext();
d.validate({}); // returns true, console.log never triggered
d.validate({hello: null}); // returns false, console.log never triggered
d.validate({hello: 'world'}); // returns false, console.log never triggered
```

What am I doing wrong?

**Comment by lourd** [comment] 2015-04-08 19:06
Ok, I understand why it's not being ran now. Since the `documentSchema` doesn't have any keys it won't run any validators. In addition, if it did have keys but the document being passed in doesn't have any of those keys, it still won't run the validators. In both cases it just lops off the key-value pairs.

So with that as it is, how would you define a flexible key schema? The keys can be any string but the value must be a certain format.

**Comment by cmnjcs** [comment] 2015-05-20 17:10
Bump. Running into the same thing--have an object with keys that are Mongo IDs, but not known in advance, but all the values will have the same structure and want to validate them.

**Comment by aldeed** [comment] 2015-11-10 20:42
Duplicate of #213

**Closed by aldeed** 2015-11-10 20:42 UTC
